### ISSUE TITLE
fix: 회원가입시 이메일 중복체크 로직 

### ISSUE THREAD

**Issue by dev1week** [D-Nolja/Server#10]
## Description ✏
- 회원가입시 이메일 중복 체크 로직을 설정합니다. 

## Todo 📝
- [x] db 스키마 수정 ( user_name 칼럼이 아닌 email을 unique로 변경해야한다. 
- [x] email로 검색해 온 후 있다면 duplicatedError 반환
- [x] duplicatedError 핸들러 작성
