### ISSUE TITLE
user 로그인 

### ISSUE THREAD

**Issue by dev1week** [D-Nolja/Server#12]
## Description ✏
- security 연동하여 기본적인 로그인 기능
- jwt 연동하여 email + password 기반 로그인 로직 구현 

## Todo 📝
- [x] verification 여부 체크 
- [x] verification 예외 정의
- [x] verification 핸들링 
- [ ] 기본적인 로그인 로직 

## ETC 📌
- 남길 말을 적어주세요.
